### PR TITLE
add Carthage support

### PR DESCRIPTION
**Pull request by dstranz**
Hello @jamesruston 

I would like to add Carthage support for your library. To do that I need to mark existing CodableExtensions Xcode scheme as shared.

I've added also a bit of instruction how to install it via Cocoapods & Carthage and Carthage compatible badge to README file.

### CODE REVIEW

**Comment by jamesruston** [comment]
Looks good 👍 thanks for the contribution

**Comment by dstranz** [comment]
@jamesruston There is a one more thing to do. Carthage is trying to use latest release tag. Could you add new one with my change?

**Comment by jamesruston** [comment]
I've created a 0.2.2 tag now, let me know if that resolves the issue for you.

**Comment by dstranz** [comment]
Yes, now it's fine! Thank you!

```bash
carthage update
*** Fetching CodableExtensions
*** Checking out CodableExtensions at "0.2.2"
*** xcodebuild output can be found in /var/folders/l8/sg5821hn6xqbxdw6lw0rznnc0000gn/T/carthage-xcodebuild.KAzaVy.log
*** Building scheme "CodableExtensions" in CodableExtensions.xcworkspace
```

**Pull request merged**
